apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-devops-project
  labels:
    app: node-js-devops-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-js-devops-project
  template:
    metadata:
      labels:
        app: node-js-devops-project
    spec:
      containers:
        - name: node-js-devops-project
          image: jibin321/node-js-devops-project:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
